### ISSUE TITLE
Crashes playdate

### ISSUE THREAD

**Issue by mintdotco** [scratchminer/Index-OS#13]
Just says you need to restart your play date. I have а revision 2 playdate

**Comment by scratchminer** [comment]
Can you check the crashlog? I think this might have something to do with the other crash

**Comment by mintdotco** [comment]
I’ll check it when I get back home because I only have my cellphone right now

**Comment by mintdotco** [comment]
I'm not sure which one to give you, so i'll give you both

**Comment by mintdotco** [comment]
[crashlog.txt](https://github.com/scratchminer/Index-OS/files/12441709/crashlog.txt)
[errorlog.txt](https://github.com/scratchminer/Index-OS/files/12441710/errorlog.txt)

**Comment by mintdotco** [comment]
Did you see it?

**Comment by scratchminer** [comment]
Yep, I think I figured it out. To work correctly, the code needs to know whether the Playdate it's running on is Revision B, and I messed the detection code up.

**Comment by scratchminer** [comment]
Alright, now it should work. I don't have a Rev. B device myself, so if you want to you can test it.
