### ISSUE TITLE
"Couldn't find pdz file main.pdz"

### ISSUE THREAD

**Issue by sks316** [scratchminer/Index-OS#18]
I sideloaded the Index Installer via the Playdate website, but got this error after launching it:
`Couldn't find pdz file main.pdz`
Seems like a fairly trivial issue, but when I looked in the pdx.zip file I uploaded, the main.pdz file clearly exists.
If it matters at all, I'm using a Rev B console running the latest Playdate OS 2.2.0.

**Comment by scratchminer** [comment]
...that's super weird, I'll have to take a look. My guess is that there's a bug in Panic's sideload server -- this has happened before.

**Comment by scratchminer** [comment]
> running the latest Playdate OS 2.2.0

Oh, whoops. Yeah, I'll get a patch out for that FW version.

**Comment by scratchminer** [comment]
alright, try Index OS v1.3.5. I've updated the shenanigans to work with firmware 2.2.0

**Comment by sks316** [comment]
It works perfectly now, thanks!
Some of the animations seem a bit rough compared to the stock launcher, but I'm already impressed.
