### ISSUE TITLE
Crash while scrolling after exiting game

### ISSUE THREAD

**Issue by Brogarrett** [scratchminer/Index-OS#4]
Using v1.0.4, if I try to scroll either after exiting a game, or closing the menu, Index crashes. It seems like I'm trying to scroll up before the game-list is generated and scrolling interrupts that process. 

Crash report:
`views/cardView.lua:247: method 'queueIdle' is not callable ( a nil value)
stack traceback:
views/cardView.lua:247: in upvalue 'loadAll'
views/cardView.lua:1721: in method 'draw'
main.lua:443 in function <main.lua:440>`

**Comment by scratchminer** [comment]
That does indeed seem like the issue. I can reproduce this on the latest version (v1.0.5) scrolling with the crank. I think I might be able to fix it if I generate the game before its card images are loaded.

**Comment by scratchminer** [comment]
I fixed your issue at the cost of a bit of lag when you scroll quickly.
