### ISSUE TITLE
Full screen title card

### ISSUE THREAD

**Issue by Brogarrett** [scratchminer/Index-OS#5]
I have two games (by the same developer), instead of a title card a full-screen animation plays. In Panic OS, the title card is (I think) the first frame of the animation (restricted to the card size). So possible there is an issue with how the title card animation is packaged in the .pdx file. Minor issue, up to you if you want to force/resize title cards appropriately.

**Comment by scratchminer** [comment]
Which games are these? I haven't seen this issue yet, so could you please upload a Mirror video or something?
(Also, can you look inside the game bundle and check if the folders are named correctly? The title card animation folder should be named `card-highlighted` and the launch animation folder should be named `launchImages`.)

**Comment by Brogarrett** [comment]
I'm not sure the best way to share the videos, but here's an imgur link. If there's additional info the mirror gives, I'll get that working instead: https://imgur.com/a/YrMH2Fj

For both games, pdxinfo lists imagePath=SystemAssets/, Inside SystemAssetts is folder card-highlighted with files 1.pdi (through 4.pdi) and 'animation.txt', and the base SystemAssets contains files card.pdi, card-pressed.pdi and launchImage.pdi

I haven't really used the simulator, but I can get that working and see which files are being pulled for the card/animation.

**Comment by scratchminer** [comment]
Interesting. From your description of four card images, it seems that the card images should be cropped if they're fullscreen. Not many games rely on this functionality, but it does seem to be implemented in Panic's launcher and is evidently used by more than one game. I'll get that into the next release.

**Comment by scratchminer** [comment]
I've just released version 1.0.6, which should fix the two issues you raised. Let me know if this doesn't fix the problem, and I'm closing this issue for now.

**Comment by Brogarrett** [comment]
Thanks, although I'm not sure that is the problem, since the Panic launcher isn't playing the animations, so it looks like it's just pulling a different file. Not sure if this is really an issue, but when refreshing my games list from the settings, it didn't register 1.0.6 as a new version from 1.0.4 to be updated, so I needed to delete local data and reinstall. The version number 1.0.6 and 1.0.4 does show correctly, so I'm not sure what is happening there.
