### ISSUE TITLE
"This installer is meant for real hardware" error appearing on hardware

### ISSUE THREAD

**Issue by chellman** [scratchminer/Index-OS#6]
Does IndexOS need to be updated for Playdate OS 2.0.0, perhaps?  I just tried sideloading onto my actual device running 2.0.0 and got that error.

**Comment by scratchminer** [comment]
It does indeed -- and actually I'm about to publish Index 1.1.0 now, which should fix the issue on OS 2.0 Playdates (and break it on 1.13.7 Playdates).

**Comment by chellman** [comment]
Thanks - I tried installing and uninstalling, and both worked great.  You've done a very nice job with this!
