### ISSUE TITLE
Issues with 'new folder' screen

### ISSUE THREAD

**Issue by R0M4N0F5K7** [scratchminer/Index-OS#7]
Thank you for this nice piece of hacky software, I finally got around to testing it. Very impressive, but got plenty of feedback nonetheless if that's okay.
(Saw this is all(?) written in lua. Are push/merge requests encouraged/appreciated if someone is to tweak/add something they like?)

But now for the actual issues with the new folder screen:

1) Sometimes when deleting letters the folder icon next to the 'New Folder Name:' label will disappear and the title shift to the right.

2) Sometimes the input characters will slip downwards halfway under the keyboard.

3) Sometimes pressing A or B will register multiple times.

After playing around for a while it seem like 1) and 2) is caused when selecting a character with A, then moving in any direction and then pressing B.
Not sure if 3) is related to that, it seems to get worse the more often I repeat that process though.

**Comment by scratchminer** [comment]
Hmm, interesting. Those issues could have been introduced when I fixed the "new folder" screen, so I'll take a look. Thanks for reporting the bug!

To answer your first question. the feature set isn't expected to change much, so feel free to add a pull request if you want!

**Comment by scratchminer** [comment]
This should be fixed in the latest commit -- for some reason a typo in `newFolderView.lua` caused it.
